name: Dodops blog
description: Blogando sobre desenvolvimento
meta_description: "Dodops Blog - Dev Web"
aboutPage: true
markdown: kramdown
highlighter: rouge
paginate: 20
baseurl: /
domain_name: 'http://dodops.github.io'
google_analytics: 'UA-77295148-1'
disqus: true
disqus_shortname: 'dodops'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://dodops.github.io'
author:         'Douglas Macedo'
authorTwitter:  'dodop3'
permalink:       /:year/:title/
defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
